#!/usr/bin/env node

/**
 * Standalone Live Task Dashboard
 * Generated by Like-I-Said MCP Server installer
 */

import { spawn } from 'child_process';
import path from 'path';

// Path to the MCP server (adjust if needed)
const MCP_SERVER_PATH = '/mnt/d/APPSNospaces/like-i-said-mcp';
const WATCH_SCRIPT_PATH = path.join(MCP_SERVER_PATH, 'watch-tasks.js');

// Auto-detect project name from current directory
const projectName = path.basename(process.cwd());

// Forward all arguments to the original script, adding project if not specified
const args = process.argv.slice(2);
if (!args.some(arg => arg.startsWith('--project='))) {
  args.push(`--project=${projectName}`);
}

// Spawn the original watch-tasks.js script
const child = spawn('node', [WATCH_SCRIPT_PATH, ...args], {
  stdio: 'inherit',
  cwd: MCP_SERVER_PATH
});

child.on('exit', (code) => {
  process.exit(code);
});

child.on('error', (error) => {
  console.error('❌ Failed to start Live Task Dashboard:', error.message);
  console.error('💡 Make sure Like-I-Said MCP server is installed at:', MCP_SERVER_PATH);
  process.exit(1);
});
