name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Basic build and test job
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [18.x, 20.x]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"
          
      - name: Install dependencies
        run: npm ci --include=dev
        env:
          GITHUB_ACTIONS: true
          CI: true
          NODE_ENV: development
        
      - name: Build project
        run: npm run build
        env:
          GITHUB_ACTIONS: true
          CI: true
        
      - name: Check TypeScript
        run: npx tsc --noEmit || echo "TypeScript check failed but continuing"
        continue-on-error: true
        
      - name: Run MCP protocol tests
        run: npm test
        timeout-minutes: 5
        env:
          GITHUB_ACTIONS: true
          CI: true
          NODE_ENV: test
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            *.log
            test-results/
            npm-debug.log*

  # Simplified Windows environment testing - focus on standard setup
  test-windows-simplified:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Verify Node.js Installation
        run: |
          Write-Host "Node version: $(node --version)"
          Write-Host "npm version: $(npm --version)"
          Write-Host "Platform: $env:OS"
        shell: powershell

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Working directory: $(pwd)"
          echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
          echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"
          
      - name: Install dependencies
        run: npm ci --include=dev
        env:
          GITHUB_ACTIONS: true
          CI: true
          NODE_ENV: development

      - name: Build project
        run: npm run build
        env:
          GITHUB_ACTIONS: true
          CI: true

      - name: Run basic tests
        run: npm test
        env:
          GITHUB_ACTIONS: true
          CI: true
          NODE_ENV: test

      - name: Test global package creation
        run: |
          npm pack
          Write-Host "Package created successfully"
        shell: powershell
        continue-on-error: true

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-windows-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            *.log
            build/
            test-results/
